# Generated by Django 3.1.7 on 2021-09-28 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0008_auto_20210917_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryListOtherUserConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.otheruser')),
                ('secondary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.secondarylist')),
            ],
        ),
        migrations.AddField(
            model_name='secondarylist',
            name='other_users',
            field=models.ManyToManyField(through='referral.SecondaryListOtherUserConnector', to='referral.OtherUser'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_user_id', models.CharField(default='none', max_length=500)),
                ('amount', models.CharField(default='none', max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryListOtherUserConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.otheruser')),
                ('primary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.primarylist')),
            ],
        ),
        migrations.AddField(
            model_name='primarylist',
            name='other_users',
            field=models.ManyToManyField(through='referral.PrimaryListOtherUserConnector', to='referral.OtherUser'),
        ),
    ]
