# Generated by Django 3.1.7 on 2021-08-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='paid_status',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='pfc_status',
            new_name='payment_status_k',
        ),
    ]
