# Generated by Django 3.1.7 on 2021-09-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20210826_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
    ]
