# Generated by Django 3.1.7 on 2021-09-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_investment_ha_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='harvest_amount',
            field=models.IntegerField(default=0),
        ),
    ]
