# Generated by Django 3.1.7 on 2021-09-03 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_investment_harvest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='switch_date30',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='switch_date7',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
