# Generated by Django 3.1.7 on 2021-09-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_auto_20210903_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
