# Generated by Django 3.1.7 on 2021-10-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_auto_20210917_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='harvest_amount',
            field=models.FloatField(default=0),
        ),
    ]
