# Generated by Django 3.1.7 on 2021-10-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0010_investment_lock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='auth_code',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='appuser',
            name='auth_status',
            field=models.BooleanField(default=False),
        ),
    ]
