# Generated by Django 3.1.7 on 2021-12-25 03:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0011_auto_20211010_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=500)),
                ('amount', models.CharField(default='none', max_length=500)),
                ('image', models.FileField(blank=True, default='default_files/default.png', upload_to='app_files/proof_photos/')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NftClaimerConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.claimer')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.nft')),
            ],
        ),
        migrations.AddField(
            model_name='nft',
            name='claimers',
            field=models.ManyToManyField(through='app_user.NftClaimerConnector', to='app_user.Claimer'),
        ),
    ]
