# Generated by Django 3.1.7 on 2021-11-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0015_appuser_auth_str'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='auth_str',
            new_name='otp_code',
        ),
    ]
