# Generated by Django 3.1.7 on 2021-11-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0016_auto_20211102_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='otp_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='otp_status',
            field=models.BooleanField(default=False),
        ),
    ]
