# Generated by Django 3.1.7 on 2021-11-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0017_auto_20211103_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='otp_choice',
            field=models.BooleanField(default=True),
        ),
    ]
